### PR TITLE
[WIP] Bootstrapifying

### PR DESCRIPTION
**Pull request by sroberts**
Adding Bootstrap and creating some CSS/JSified views.

### CODE REVIEW

**Comment by sroberts** [comment]
Still a work in progress, but here's how things look so far:

## Configuration Groups
screen shot 2015-09-13 at 11 44 31 am

## Configuration Creator
screen shot 2015-09-13 at 11 44 39 am

## Configuration Details
screen shot 2015-09-13 at 11 45 26 am

Feedback is welcome!

**Comment by blackfist** [comment]
I like the way this is looking! Clean and neat. I've done some pushing to master that you'll have to resolve but this is great so far. :+1:

**Comment by blackfist** [comment]
Arrr, you have checked in your `.ruby-version`. Please to be putting that in your .gitignore so that it doesn't conflict with mine.

**Comment by blackfist** [comment]
There is also a fair amount of code duplication in the html for those different files. I might recommend that you create a `layout.erb` file in `/views` and put most of the code there. Then just use a `<%= yield %>` in that file where the unique content would normally go.

**Pull request merged**
